// This file is auto-generated by generatePonderConfig.ts
// Do not edit manually - changes will be overwritten

import { mainnet } from "viem/chains";

export const chainConfigs = {
  chains: {
    mainnet: {
      chainId: 1,
      transport: "https://eth-mainnet.g.alchemy.com/v2/",
    },
    arbitrum: {
      chainId: 42161,
      transport: "https://arb-mainnet.g.alchemy.com/v2/",
    },
    base: {
      chainId: 8453,
      transport: "https://base-mainnet.g.alchemy.com/v2/",
    },
    optimism: {
      chainId: 10,
      transport: "https://opt-mainnet.g.alchemy.com/v2/",
    },
  },
  ethSplitterContracts: {
    mainnet: {
      address: "0x92A66A3E5F8DA48B17EB48825487a1698D1c5519" as `0x${string}`,
      startBlock: 18726817,
    },
    arbitrum: {
      address: "0x43CfBD8e59bfE79Cb795f123751381912c267c53" as `0x${string}`,
      startBlock: 370217088,
    },
    base: {
      address: "0x6A8A356C2Fdb6d4004e785ADd08Af7e085a1432a" as `0x${string}`,
      startBlock: 34427536,
    },
    optimism: {
      address: "0x4E64AFA9a309B42B3F1E985F2a8F951cACAB7633" as `0x${string}`,
      startBlock: 140022866,
    },
  },
};
